### ISSUE TITLE
Ability to specify file in template tag

### ISSUE THREAD

**Issue by rey-wright** [owais/django-webpack-loader#10]
Hi.

So I'm currently using django-webpack-loader in order to make react-hot-loader work. The thing is, is I have 2 entry points which both output their own file. I would like the ability to specify a specific file, rather than (what I think I would have to do) create an entirely different webpack config file & associated npm scripts to go with it.

Normally this wouldn't make sense (e.g. why not just build the files and reference them directly in the template) however again... I'm using react-hot-loader. Any advice on how to proceed?

**Comment by destos** [comment]
@rey-wright you should be able to name your entry points by turning your entry list into an object with
```javascript
entry: {
<first name>: <entry script>,
<second name>: <entry script>
}
```
Then just call something like this in your template:
```jinja
{% render_bundle '<first name>' %}
{% render_bundle '<second name>' %}
```

Haven't tried this, but I think that's how it should work

**Comment by owais** [comment]
@destos is right. It should work this way. If it doesn't, let me know and I'll try to fix the issue. It works for automatic code splitting like in this example: https://github.com/owais/django-webpack-loader/tree/master/examples/code-splitting

**Comment by rey-wright** [comment]
Thank you. I was trying that and it was throwing a Django error but I think it was because it wasn't compiling correctly. Thanks.
