### ISSUE TITLE
misleading commentary in readme

### ISSUE THREAD

**Issue by vadimadr** [owais/django-webpack-loader#100]
Example in readme states that BUNDLE_DIR_NAME option must be ended with slash:
```python
WEBPACK_LOADER = {
    'DEFAULT': {
        'BUNDLE_DIR_NAME': 'bundles/' # end with slash
    }
}
```
However, I wanted webpack configuration that outputs bundle in root of staticfiles dir, so I created configuration like this:
```python
WEBPACK_LOADER = {
    'DEFAULT': {
        'BUNDLE_DIR_NAME': '/',
        'STATS_FILE': os.path.join(ROOT_DIR, 'webpack-stats-dist.json'),
    }
}
``` 
And it lead me to pity errors as my staticfiles storage class was unable to find url for appropriate bundle files. `'BUNDLE_DIR_NAME': ''`, obviously, works.

I think this should be clarified.

**Comment by owais** [comment]
Thanks for reporting @vadimadr. `/` represents the root of your filesystem on posix systems so it's perhaps self explanatory but yes, some more clarification would be nice. I'll update the ReadMe soon. Thanks
