### ISSUE TITLE
WebpackLoaderBadStatsError during bundling

### ISSUE THREAD

**Issue by mehdipourfar** [owais/django-webpack-loader#101]
I'm trying to bundling my asset files in production server. Everything works fine except that during building the bundle which takes about 20 seconds, anyone trying to visit the site will get 500 error. The error is as  follows as far as it is concerned with webpack_loader:

File ".../lib/python3.5/site-packages/webpack_loader/contrib/jinja2ext.py" in <lambda>
  9.         environment.globals["render_bundle"] = lambda *a, **k: jinja2.Markup(render_bundle(*a, **k))

File ".../lib/python3.5/site-packages/webpack_loader/templatetags/webpack_loader.py" in render_bundle
  40.     return render_as_tags(_get_bundle(bundle_name, extension, config), attrs)

File ".../lib/python3.5/site-packages/webpack_loader/templatetags/webpack_loader.py" in _get_bundle
  32.     bundle = get_loader(config).get_bundle(bundle_name)

File ".../lib/python3.5/site-packages/webpack_loader/loader.py" in get_bundle
  97.             "The stats file does not contain valid data. Make sure "

I should mention that in production settings, I already have set webpack loader cache to True:
WEBPACK_LOADER['DEFAULT']['CACHE'] = True

**Comment by mehdipourfar** [comment]
Any news? If you have no time I can contribute to your project.

**Comment by owais** [comment]
You should not be compiling your static assets on a live site. Ideally, the compilation/bundling should happen on a CI server (or from wherever you deploy) and the stats file should be delivered to the the servers along with he updated python code.

If you still want to do this on the server, I suggest to make webpack output to a different file and make django read from a different one. You deploy script can look something like this:

```
- update code
- run webpack # generates webpack-stats.json
- if webpakc build succeeds:
    - copy `webpack-stats.json` to `webpack-stats-live.json`
    - restart django server
- else:
    - rollback the update
```

In this case, django will only ready from `webpack-stats-live.json` but webpack would generate `webpack-stats.json`. Then your build/deploy script can have a simple `cp webpack-stats.json webpack-stats-live.json` command to replace the old stats file with the new one.

**Comment by mehdipourfar** [comment]
The problem with client side compiling is that it will make repository full of heavy and useless codes. I think  production server should always works the same until restarting (or reloading) workers.  And in case of webpack loader, it should read webpack-stats.json once and return the same link until next restart. Raising error on production server because of changing a json file is not very good.

**Comment by mehdipourfar** [comment]
From documentation: 

> When CACHE is set to True, webpack-loader will read the stats file only once and cache the result. This means web workers need to be restarted in order to pick up any changes made to the stats files.

All that I want to say is that this feature doesn't work properly.

**Comment by owais** [comment]
OK. Can you please share more details about your production setup? It would be great if you could create a simple, bare minimum example project and share on github.

**Comment by mehdipourfar** [comment]
I can't reproduce the issue anymore. I don't know what to say. I will inform you whenever errors reappear again.

**Comment by owais** [comment]
No worries. Feel free to re-open this if needed.

**Comment by orioncx** [comment]
+1
Production settings:
`WEBPACK_LOADER = {
    'DEFAULT': {
        'CACHE': not DEBUG,
        'BUNDLE_DIR_NAME': 'dist/',  # must end with slash
        'STATS_FILE': os.path.join(SITE_ROOT, 'webpack-stats.json'),
        'POLL_INTERVAL': 0.1,
        'TIMEOUT': None,
        'IGNORE': ['.+\.hot-update.js', '.+\.map']
    }
}` 
But during compilation below error occurs:
`WebpackLoaderBadStatsError: The stats file does not contain valid data.`
variables values:
`assets	
{
u'publicPath': u'/static/multime3/dist/', 
u'status': u'compiling'
}
bundle_name	
u'manifest'`
As I see in documentation assets should be cached and reloaded only when supervisord restarts. But it doesn't work.

**Comment by orioncx** [comment]
Hack with 
- copy `webpack-stats.json` to `webpack-stats-live.json`
solves problem, but according documentation it shouldn't be neccessary

**Comment by aguynamedben** [comment]
+1 This issue resulted in confusing and embarrassing downtime of 500s during my deploy.

I agree with @mehdipourfar and @orioncx that the CACHE feature doesn't work. It's trivial to reproduce, just reload your server while running Webpack. When Webpack is running, webpack-stats.json becomes:

```json
{"status":"compiling","publicPath":"https://staging-cdn.mineralsoft.com/static/webpack_bundles/"}
```

When django-webpack-loader encounters that, you get WebpackLoaderBadStatsError, resulting in a 500 during deploys.

**Comment by aguynamedben** [comment]
Also, the workaround makes me unnecessarily have to have different settings in WEBPACK_LOADER for development vs. production (i.e. in development I want to keep it "normal" with webpack-stats.json, not webpack-stats-live.json + the file copy).

**Comment by aguynamedben** [comment]
This issue should at least be re-opened...

**Comment by aguynamedben** [comment]
[Current docs](https://github.com/ezhome/django-webpack-loader#cache) say:

> When CACHE is set to True, webpack-loader will read the stats file only once and cache the result. This means web workers need to be restarted in order to pick up any changes made to the stats files.

[Changelog in 0.3.0](https://github.com/ezhome/django-webpack-loader/blob/fbda06fe2be61d7d7e8a9c28dfa01c0c3badfcdb/CHANGELOG.md) says:

> - breaking 💥: new CACHE setting which when set to true makes the loader cache the contents of the stats files in memory. If set to True, server will restart every time the stats file contents change or it'll keep serving old, cached URLs. CACHE defaults to not DEBUG by default.

[Code](https://github.com/ezhome/django-webpack-loader/blob/14af9a21c0e044c572f2b1dc90a2e4ff3ff05329/webpack_loader/loader.py#L34) says:

```py
    def get_assets(self):
        if self.config['CACHE']:
            if self.name not in self._assets:
                self._assets[self.name] = self._load_assets()
            return self._assets[self.name]
        return self._load_assets()
```

The way this function is written, with `return self._load_assets()`, won't the assets be loaded every time `get_assets()` is called? Should it be this instead?

```py
    def get_assets(self):
        if self.config['CACHE']:
            if self.name not in self._assets:
                # It's the first time, load from file
                self._assets[self.name] = self._load_assets()
            return self._assets[self.name]
        else:
            # Always load from file
            return self._load_assets()
```

**Comment by aguynamedben** [comment]
^^^ I submitted a PR that fixes this. It was a very simple code scoping issue.

**Comment by aguynamedben** [comment]
Nevermind, my bug fix doesn't fix the issue. :( Still looking at it.

**Comment by aguynamedben** [comment]
I just messed with this for a few hours.

1. CACHE is working, but it's very nuanced. The docs state "webpack-loader will read the stats file only once". I took this to mean "when the server starts, webpack-stats.json will be ready and not updated until the server restarts. From what I can tell by testing the code, webpack-stats.json is read on the first page load.

2. Most of my problems were due to pasting the default config into settings.py, and not overriding things properly in settings_staging.py and settings_production.py. When I read the README, I saw the config block and pasted it into settings.py. CACHE has the value `not DEBUG`. When Django loads, settings.py loads first. My settings.py has DEBUG = True, so CACHE was getting set to False, **even in staging and production** where DEBUG = True. This is because `not DEBUG` was executed within the context of settings.py. What I did to fix this was in settings_staging.py and settings_production.py putting:

```py
WEBPACK_LOADER['DEFAULT']['CACHE'] = True
```

However, because webpack-stats.json is loaded on first read, not startup, I ended up also putting this in settings_staging.py and settings_production.py:
```py
WEBPACK_LOADER['DEFAULT']['STATS_FILE'] = 'webpack_bundles/webpack-stats-live.json'
```

And in my staging/production Upstart script (gunicorn.sh) adding this step before starting gunicorn:
```sh
cp /home/myuser/mysite/webpack_bundles/webpack-stats.json /home/myuser/mysite/webpack_bundles/webpack-stats-live.json

exec ./bin/gunicorn \
    -b 0.0.0.0:8001 \
    -w 10 \
    --timeout 120 \
    --max-requests 100 \
    --max-requests-jitter 10 \
    minerals.wsgi:application
```

I still thing the behavior/documentation of CACHE is confusing. It didn't work like I expected, partially due to the README leading me to paste the default config into settings.py, and partially because I still don't fully understand when webpack-stats.json gets loaded.

Maybe down the road this could be cleaned up by very explicitly reading webpack-stats.py on server startup/WebpackLoader initialization.

**Comment by konstin** [comment]
I had the same problem and found a different solution: For `DEBUG=False` I store the webpack-stats.json with the assets and make django use the stats from the static folder. When I run `collectstatic` after the webpack build, it will replace the finished stats file with another finished stats file. On `DEBUG=False` I simple use the stats file from the location where it will be collected.

Webpack config:

```javascript
        new BundleTracker({
            path: path.resolve(__dirname, '../mainapp/assets/bundles'),
            filename: './webpack-stats.json'
        }),
```

Django config:

```python
if DEBUG:
    webpack_stats = "mainapp/assets/bundles/webpack-stats.json"
else:
    webpack_stats = os.path.join(STATIC_ROOT, "bundles", "webpack-stats.json")

WEBPACK_LOADER = {
    "DEFAULT": {
        "BUNDLE_DIR_NAME": "bundles/",
        "STATS_FILE": webpack_stats,
    }
}
```

**Comment by caymard** [comment]
@konstin your method works like a charm on my project, thanks :)

**Comment by caymard** [comment]
@konstin on a second look, this method involves that the file is accessible publicly, not that great. But the principle is great though.
