### ISSUE TITLE
Typo & suggestion for production webpack config

### ISSUE THREAD

**Issue by dopeboy** [owais/django-webpack-loader#13]
Hi again,

1) In the blog post [here](http://owaislone.org/blog/webpack-plus-reactjs-and-django/), at the very bottom under the webpack.prod.config.js section, the following edit should be made:

```config.output.pathName =>  config.output.publicPath```

2) This is more of a suggestion but it wasn't obvious to me what I had to do to remove the hot loader from the production webpack config. Perhaps a line like so

```config.entry = ['./assets/js/index']```

might be helpful. That way, regardless of whether people are hot loading or not in their development webpack config, their production config won't contain it. 

Just want to reiterate a big thank you to @owais. Your guide and plugin have been tremendously useful.

Manish

**Comment by owais** [comment]
Thanks. Updated.
