### ISSUE TITLE
integration  with @angular/cli

### ISSUE THREAD

**Issue by rrauenza** [owais/django-webpack-loader#139]
I *really* like this module and started using it with webpack+react - but we're switching to angular.

....But angular cli doesn't give us access to the webpack config underneath (which more or less performs a bunch of magic and dumps N files into a dist directory.)

I'm tempted to just write a script that renames those N files to have a hash and then creates my own status.json to be loaded by Django.

So this is sort of a vague enhancement request -- any ideas on how to make this work mostly seamlessly with angular cli?  (even if its just a script I call afterwards.)

**Comment by domsew** [comment]
You can use [ng eject](https://github.com/angular/angular-cli/wiki/eject) to get webpack config.

**Comment by owais** [comment]
I've not used angular a lot so can't comment. That said, if your script produces stats.json output compatible with webpack-bundle-tracker, I think you can use it with django-webpack-loader 100%.

**Comment by AWinterman** [comment]
you can no longer angular eject. I'm about to embark on figuring out how to make this work for ng build --prod. I'll report back once I figure it out, but I think we might want to reopen this for now.

**Comment by Dviejopomata** [comment]
@AWinterman  I'm having the same problem, did you find any solution?
