### ISSUE TITLE
Multiple STATS_FILE support

### ISSUE THREAD

**Issue by cybercase** [owais/django-webpack-loader#14]
I'm working on a project that has multiple webpack config files (one for each django app), so I was thinking to add support for multiple webpack-stats.json files...
something like:

```
WEBPACK_LOADER = {
    ...
    'STATS_FILE': ('webpack-stats-app1.json', 'webpack-stats-app2.json'),
    ...
}
```

Is it ok for you if I add this feature and submit a PR? 
Or do you think there is a better way to deal with multiple webpack config files?

Thanks

**Comment by owais** [comment]
This request has come up before a couple of times as well. We could add support to the bundle tracker plugin to make it write namespaced or prefixed stats so multiple configs would write to the same file OR we could add support to webpack-loader to be able to read multiple stats files.

I think adding support to webpack-loader would probably be more flexible although it requires a bit more work than doing so for bundle-tracker.

If you could submit a PR, that would be great but lets make the config look like this,

```
WEBPACK_LOADER = {
    'DEFAULT': {
         'STATS_FILE': 'webpack-stats-app1.json',
         ....     
     },
     'APP2': {
         'STATE_FILE': 'webpack-stats-app2.json',
     }
    ...
}
```

Then in templates we would have to add support for an additional parameter to specify the file we want like

```
{% render_bundle 'main' extension='css'  config='APP1' %}
```

`config` parameter can be optional and  resolve to `DEFAULT` by default :)

I'm OK with breaking backward compatibility for this and bumping the version to 1.0 but it would be nice to add a django system check and bail out with an error explaining that the user is using pre 1.0 config.

**Comment by cybercase** [comment]
Thanks for you quick reply.
I think I'll start soon to work on this feature :)
