### ISSUE TITLE
Handling deploys

### ISSUE THREAD

**Issue by trent** [owais/django-webpack-loader#151]
I have this deployed successfully and it's working great.  Thanks!  

I'm curious how you suggest handling deployments of new code for a single page application, though.  The SPA is a dashboard which can often stay up in a user's browser for days or weeks without a page refresh.  With `render_bundle` statically rendering the script tag in the template markup, my deployment will push a new bundle with a new hash, but the client template is never re-rendered to pull the bundle.  So how would one go about notifying the client to refresh the browser page, or dynamically loading the bundle on change?

**Comment by jpic** [comment]
Did you try a timer to check for an update and then update the script tags in the dom ?

**Comment by jpic** [comment]
https://github.com/ezhome/django-webpack-loader/tree/master/examples/hot-reload

**Comment by trent** [comment]
I'm running hot-reload in local development and it works great, but I'm more interested in how to handle this in a production deployment.

**Comment by ogonkov** [comment]
It's not related to this Django app

But you could set some cookie in your django app, and set it value on JS app init
Then check this cookie, when you pull fresh data, and refresh or show some dialog when new build is available

**Comment by owais** [comment]
It's not something this package does or should handle but it's pretty simple to implement with a little bit of work. At work, we add a periodic function to the app that runs every 5 minutes or so. It downloads the index.html page and checks the contents with the contents of the current index.html and if there is a diff, the app displays a banner at top prompting the user to refresh the page to get latest updates. This works as most apps are internal admin dashboards but some variation of this should work for any app.
