### ISSUE TITLE
Polyglot XHTML Support

### ISSUE THREAD

**Issue by basicdays** [owais/django-webpack-loader#17]
Hey!

I gotta say that I find this project to be fantastic and everything is working amazingly well. I'd like like to ask though, that the output markup is polyglot markup. Pretty much the only thing that would need to be done is adding an ending `/` to the link tag in https://github.com/owais/django-webpack-loader/blob/master/webpack_loader/templatetags/webpack_loader.py.

If this is an acceptable idea to you, I can go ahead and create a PR for this change.

**Comment by owais** [comment]
Sure. Go ahead please.
