### ISSUE TITLE
Generating the correct path for images

### ISSUE THREAD

**Issue by dopeboy** [owais/django-webpack-loader#20]
(This is more a question around understanding and clarification rather than a proposal for a specific fix). 

Going off this [guide](http://owaislone.org/blog/webpack-plus-reactjs-and-django/): is there a reason why a file-loader is not needed in the production webpack config? 

When I don't include it and I use a `require('.../img.png')` in my application code, webpack correctly finds the image, renames it based on the hash, dumps it in the right place, and sets the path correctly. In other words, everything works OK.  

Per all the [documentation](https://github.com/webpack/file-loader) I've read on webpack, there are explicit recommendations to put the following in one's config file:
  
```
  module: {
    loaders: [
      { 
...
	  { test: /\.(png|jpg)$/, loader: 'file-loader'} 
    ],
  },
```

If I include the above, webpack generates another file that's either malformed or just some dummy stub.

**Comment by owais** [comment]
I think it is best to ask this on webpack or one of it's loader's github/gitter/slack/. The people that wrote webpack and file-loader/url-loader are best suited to explain how these things work. 

https://github.com/webpack/webpack

https://github.com/webpack/file-loader
