### ISSUE TITLE
Why would one prefer 'django-webpack-loader' over 'html-webpack-plugin'

### ISSUE THREAD

**Issue by ejez** [owais/django-webpack-loader#209]
I tried to see if I need to use 'django-webpack-loader' but still not convinced. Its objective is to allow use of the generated webpack bundles, but this can be achieved easily with 'html-webpack-plugin' which generates an html file with the bundle files injected in it, this html file then can be used as a django template.
The advantage of using 'html-webpack-plugin' becomes more obvious when using a pre-configured webpack ecosystem (like vue cli) where we get a ready made html file with all the needed head/body bundle tags (including prefetch/preload links ...) injected, without any need to manually select what to put in head/body.

Here is my setup (simplified):

`base.html`
```html
{% block html %}
<!DOCTYPE html>
<html {% block html_tag_attributes %}{% endblock %}>
  <head>
    {% block head %}
      <meta charset="utf-8">
    {% endblock %}
  </head>

  <body {% block body_tag_attributes %}{% endblock %}>
    {% block body %}
      {% block content %}{% endblock %}
    {% endblock %}
  </body>
</html>
{% endblock %}
```

`index.html` (template used by html-webpack-plugin to generate `bundles/webpack/home_page.html`):
```html
{% extends "base.html" %}
{% load static %}
{% block html %}
<!DOCTYPE html>
<html {% block html_tag_attributes %}{{ block.super }}{% endblock %}>
  <head>
    {% block head %}{{ block.super }}{% endblock %}
  </head>
  <body {% block body_tag_attributes %}{{ block.super }}{% endblock %}>
    {% block body %}{{ block.super }}{% endblock %}
  </body>
</html>
{% endblock %}
```

`home_page.html`
```html
{% extends "bundles/webpack/home_page.html" %}
{% block content %}
  Adding content here...
{% endblock %}
```
I appreciate if someone can tell if there is a scenario where we can do it only with `django-webpack-loader`

Note: the links in the injected tags can be easily converted to django static tempate tag format, ie: `'bundles/js/main.js' ==> {% static 'bundles/js/main.js' %}`
I created a minimal basic plugin to do this: https://gitlab.com/noor-projects/django-static-webpack-plugin/blob/master/index.js

@owais

**Comment by owais** [comment]
I don't know what html-webpack-plugin is and don't remember using it. I wrote this to solve my own problem a few years ago. The core problem I was trying to solve was to make it easy for Django to figure out the names of bundles generated by webpack. If html-webpack-plugin solves your problem, then I don't see why you need to use django-webpack-loader at all.

**Comment by ejez** [comment]
Thanks for the reply, I am inquiring about django-webpack-loader because I saw it mentioned in many tutorials and it is popular, so I was wondering if it has other features that I might need in the future, then I will be adopting it from the beginning.

**Comment by ejez** [comment]
I did not mean in any way to undermine django-webpack-loader, and I am sorry if that was perceived.

**Comment by jhoover4** [comment]
Html-webpack-plugin is a frontend solution to the problem, this is a backend solution. I'd say this is the easier/more manageable solution between the two.

**Comment by EugeneDae** [comment]
@ejez Thank you very much for sharing your configs! Would you mind sharing your Vue CLI config (vue.config.js) as well? 

I'm struggling a bit to understand the `html-webpack-plugin` method (because I'm new to Vue and Vue CLI), but I really want to try it.

One thing I don't understand is whether I still need the Vue dev server for anything? If not, will hot module replacement work? 

When I run the Vue dev server (`npm run serve`) from a project created via Vue CLI, it doesn't save anything to disk. One way to overcome this is to set `writeToDisk` to true, but I'm not sure if this is the most optimal way.

I wonder how you do it.

**Comment by EugeneDae** [comment]
I've created a Django + Vue CLI demo project following @ejez's approach:
https://github.com/EugeneDae/django-vue-cli-webpack-demo

I'm not advocating against django-webpack-loader — just wanted to explore an alternative.

**Comment by jpic** [comment]
It's pretty interesting indeed, I've been using both solutions, and didn't
find any reason to favor one on top of another so far.

**Comment by jpic** [comment]
I've got some updates:

- figured why I prefer django-webpack-loader over html-webpack-plugin: django-webpack-loader just saves workflow time overall, ie.: we don't have this weirdness where we edit a django base_template.html template to generate the base.html template
- migrating away from webpack to snowpack and got a 3.000x productivity boost, check [Django + Snowpack = djsnowpack blog post](https://yourlabs.org/posts/2020-10-27-django-snowpack-with-djsnowpack/)

**Comment by knokit** [comment]
@ejez, how would you use that approach on a MPA?

**Comment by EugeneDae** [comment]
> @ejez, how would you use this approach on a MPA?

might be of interest:
https://github.com/EugeneDae/django-vue-cli-webpack-demo/blob/master/README-MPA.md

**Comment by knokit** [comment]
@EugeneDae, thanks. I've read that :) However I'm not using vue, but a plain webpack config.
