### ISSUE TITLE
Update blog post with latest docs

### ISSUE THREAD

**Issue by owais** [owais/django-webpack-loader#22]

**Comment by lenards** [comment]
:+1: 

I got caught by the blog example not having the same `'DEFAULT'` dict in a dict structure. 

So, I pulled over this: 
```python
# not check
WEBPACK_LOADER = {
    'BUNDLE_DIR_NAME': 'bundles/',
    'STATS_FILE': os.path.join(BASE_DIR, 'webpack-stats.json'),
}
```

This is caught by a `./manage.py check` as not being correct. It just doesn't quite pinpoint the problem. 

You'll get an error like this: 
```
Exception Value: type object argument after ** must be a mapping, not str
```

And if you have the proper `WEBPACK_LOADER` structure, it will work (which is what's in the README.md here, shown below).

```python
WEBPACK_LOADER = {
    'DEFAULT': {
        'BUNDLE_DIR_NAME': 'bundles/',
        'STATS_FILE': os.path.join(BASE_DIR, '../webpack-stats.json')
    }
}
```

**Comment by lenards** [comment]
And thanks! :tada:

**Comment by owais** [comment]
Thanks @lenards !
