### ISSUE TITLE
Wrong version in new release

### ISSUE THREAD

**Issue by arslanhashmi** [owais/django-webpack-loader#225]
I think it has to be 0.7.0

<img width="1440" alt="Screenshot 2020-02-24 at 7 23 22 PM" src="https://user-images.githubusercontent.com/17988601/75160403-bb94ce80-573b-11ea-93e4-edd4b10d6492.png">

**Comment by arslanhashmi** [comment]
@owais can you please look into this?

**Comment by owais** [comment]
Thanks. Fixed.
