### ISSUE TITLE
issue running in django project

### ISSUE THREAD

**Issue by auvipy** [owais/django-webpack-loader#28]
Performing system checks...

Unhandled exception in thread started by <function wrapper at 0x7ff64938a848>
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/utils/autoreload.py", line 229, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/runserver.py", line 114, in inner_run
    self.validate(display_num_errors=True)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 469, in validate
    return self.check(app_configs=app_configs, display_num_errors=display_num_errors)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 528, in check
    raise SystemCheckError(msg)
django.core.management.base.SystemCheckError: SystemCheckError: System check identified some issues:

ERRORS:
django.conf.settings.WEBPACK_LOADER: (django-webpack-loader.E001) Error while parsing WEBPACK_LOADER configuration
	HINT: Is WEBPACK_LOADER config valid?

System check identified 1 issue (0 silenced).

**Comment by auvipy** [comment]
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/assets/'

# We do this so that django's collectstatic copies or 
# our bundles to the STATIC_ROOT or syncs them to whatever storage we use.

STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'assets'), 
)

WEBPACK_LOADER = {
    'BUNDLE_DIR_NAME': 'bundles/',
    'STATS_FILE': os.path.join(BASE_DIR, '../webpack-stats.json'),
}

**Comment by auvipy** [comment]
{"status":"done","chunks":{"main":[{"name":"build.js","path":"/home/asif/p/smt/opsmonitor/assets/bundles/build.js"}]}}

**Comment by auvipy** [comment]
var path = require("path")
var webpack = require('webpack')
var BundleTracker = require('webpack-bundle-tracker')

module.exports = {
  context: __dirname,

  // entry point of our app. assets/js/index.js 
  //should require other js modules and dependencies it needs

  entry: './assets/js/index', 

  output: {
      path: path.resolve('./assets/bundles/'),
      filename: "build.js",
  },

  plugins: [
    new BundleTracker({filename: './webpack-stats.json'}),
  ],

  module: {
    loaders: [

     // to transform JSX into JS
     // { test: /\.jsx?$/, exclude: /node_modules/, loader: 'babel-loader'},
      { test: /\.js$/, loader: 'babel', exclude: /node_modules/ },
      { test: /\.vue$/, loader: 'vue' }, 
    ],
  },

  babel: {
    presets: ['es2015'],
    plugins: ['transform-runtime']
  },


  resolve: {
    modulesDirectories: ['node_modules'],
    extensions: ['', '.js', '.coffee', '.jsx']
  },
}

**Comment by owais** [comment]
This is very hard to read. Can you please refer https://guides.github.com/features/mastering-markdown/ and fix the formatting :)

**Comment by auvipy** [comment]
http://codepen.io/auvipy/pen/MadWBP

**Comment by auvipy** [comment]
I added a codepen

**Comment by auvipy** [comment]
WEBPACK_LOADER = {
    'DEFAULT': {
        'BUNDLE_DIR_NAME': 'bundles/' # end with slash
    }
}


this way fixed the issue
