### ISSUE TITLE
Broken on Django 1.9: render_bundle returns escaped HTML.

### ISSUE THREAD

**Issue by nicksergeant** [owais/django-webpack-loader#30]
Release notes for 1.9: https://docs.djangoproject.com/en/1.9/releases/1.9/#simple-tag-now-wraps-tag-output-in-conditional-escape

Not entirely sure what the issue is, since it seems you're wrapping the output with `mark_safe` here: https://github.com/owais/django-webpack-loader/blob/master/webpack_loader/templatetags/webpack_loader.py#L25

**Comment by jackmccloy** [comment]
+1

**Comment by jackmccloy** [comment]
It doesn't solve the root problem, but turning autoescape off in the template where your bundle is rendered seems to be working for me. i.e.:
{% autoescape off %}
{% render_bundle 'bundle_name' %}
{% endautoescape %}

I'll try to take a closer look in the next few days unless someone beats me to it.

**Comment by nicksergeant** [comment]
Yeah that's how I fixed it temporarily, too. I attempted to fix the core issue via fork but ran into a ton of test failures in NPM related to babel-core unable to find module `'../traversal'`.

**Comment by frgtn** [comment]
`mark_safe` change is not yet released to PyPI. Tested wtih current master and it works fine with Django 1.9 in my setup.

So only thing needed for this issue is to release a new version to PyPI.

**Comment by owais** [comment]
Released `0.2.3`
