### ISSUE TITLE
Output CSS can't find font assets

### ISSUE THREAD

**Issue by BHouwens** [owais/django-webpack-loader#35]
This might be something I've screwed up, but for some reason the CSS that webpack outputs to the views can't find fonts loaded via CSS @font-face.

Example:

    @font-face {
      font-family: 'proxima_nova_rgbold';
      src: url(f1269047cfeba0c5afee919b40d06db4.eot);
     }

This is the correct output and webpack does bundle the needed assets into the correct output folder, so it should for all intents and purposes be working. But it just isn't.

**Comment by owais** [comment]
This library only gives django template the path of a JS or CSS bundle to load. It doesn't deal with fonts at all. See if it loads the fonts without using webpack-loader by temporarily replacing the `render_bundle` calls in templates with hand written `<link>` tag that refers to the CSS bundle. I doubt it'll work, but if it does then the fault lies in webpack-loader.

Also, it'll be easier to get help if you share full project config and steps to reproduce the error.
