### ISSUE TITLE
ERROR in ./assets/js/index.jsx Module build failed: SyntaxError:

### ISSUE THREAD

**Issue by tention** [owais/django-webpack-loader#37]
Am very new to webpack, was following the web blog to setup and run webpack but getting the following errors. Running Django 1.9.1.

> ERROR in ./assets/js/index.jsx
> Module build failed: SyntaxError: /Users/yensheng/virtualenvs/1fotograf/fotograf/static/assets/js/index.jsx: Unexpected token (4:13)
>  2 | var App = require('./app')
>  3 |
>  4 | React.render(`<App/>`, document.getElementById('react-app'))

My index.jsx, exactly the same as per the tutorial.
> var React = require('react')
> var App = require('./app')
>
> React.render(`<App/>`, document.getElementById('react-app'))

Error is pointing at the "<" before "App". Tried with my own react code and getting the same error at the same place. Did I missed out anything?

**Comment by owais** [comment]
Looks like a loader is missing. Please share your whole webpack config. Also, https://github.com/webpack/webpack is a better place to ask for help directly related to webpack.

**Comment by tention** [comment]
I'm using the almost same webpack config as per the guide.

>var path = require("path")
>var webpack = require('webpack')
>var BundleTracker = require('webpack-bundle-tracker')
>
>module.exports = {
>  context: __dirname,
>
>  entry: './assets/js/index', // entry point of our app. assets/js/index.js should require other js modules and dependencies it needs
>
>  output: {
>      path: path.resolve('./assets/bundles/'),
>      filename: "[name]-[hash].js",
>  },
>
>  plugins: [
>    new BundleTracker({filename: './webpack-stats.json'}),
>  ],
>
>  module: {
>    loaders: [
>      { test: /\.jsx?$/, exclude: /node_modules/, loader: 'babel-loader'}, // to transform JSX into JS
>    ],
>  },
>
>  resolve: {
>    modulesDirectories: ['node_modules', 'bower_components'],
>    extensions: ['', '.js', '.jsx']
>  },
>}

**Comment by tention** [comment]
Solved it by adding the following codes. Thanks!

Install babel-preset-react
>npm install babel-preset-react

Add presets
>{ 
>    test: /\.js$/, 
>    exclude: /node_modules/, 
>    loader: "babel", 
>    query:
>      {
>        presets:['react']
>      }
>}
