### ISSUE TITLE
webpack_static documentation

### ISSUE THREAD

**Issue by levic** [owais/django-webpack-loader#42]
There's no documentation about what `webpack_static` does (or even that it exists -- I stumbled across it looking at the source for `render_bundle`).

In particular it appears to completely bypass the error/compiling steps in `get_bundle()` -- is this intended?

**Comment by owais** [comment]
`webpack_static` is actually a bad name and I should update it. I'm not sure what to name it have not added it to docs yet as it is likely that the feature will change. It is actually a counter part to the `{% static %}` django template tag. It takes a single argument and assuming that argument is the name or relative path of a static asset like an image, and returns the full static URL of the file. It'll use `publicPath` value if defined in webpack or fallback to django's `STATIC_URL`. It is useful to get "references" to assets build/bundled by webpack in django templates. For example to load an image "images/logo.png" from your webpack bundle, you'd do,

```django
{% webpack_static "images/logo.png" %}
```

**Comment by levic** [comment]
The name made perfect sense to me; I assumed from the name it was simply a webpack equivalent of the builtin `static` tag - it was simply the lack of documentation compared to everything else that made me wonder.

If it's not stable and intended as a public interface then that makes sense that it's not documented, but that should probably be mentioned in a header comment for anyone looking at the code.

**Comment by owais** [comment]
Added to ReadMe: https://github.com/owais/django-webpack-loader/#refer-other-static-assets
