### ISSUE TITLE
Request for example pre-rendering React components with model data on the server

### ISSUE THREAD

**Issue by geezhawk** [owais/django-webpack-loader#45]
Hey,

I'm a huge fan of this tool, and thanks for documenting it so clearly. I don't have any issue with the code, but I was wondering if you might be able to provide an example that demonstrates how to pass data from Django views to react components when they render on the server? I've been trying to figure this out myself for a week now, but I'm new to webpack and so far have had no luck. Any guidance you could give would be deeply appreciated. 

Thanks again for making this!

Best,
Jonathan

**Comment by owais** [comment]
This is out of the scope of the library. This can be still done by calling node as a subprocess from within a django. I think python-webpack might be able to do that. You also try pyreact for server side rendering react components in Python. Sorry for no links, I'm on phone right now.
