### ISSUE TITLE
Hosting webpack bundle on seperate server

### ISSUE THREAD

**Issue by alphashuro** [owais/django-webpack-loader#52]
What if I want to host my webpack bundle on another server (either a docker container or normal nginx server) how would I go about doing this? do I just specify a url for the 'STATS_FILE' in the settings?

**Comment by owais** [comment]
No, you'll have to host the STATS files on the same server as Django. You can however host your actual bundles anywhere you want. Just change set `publicPath` in your webpack config to the publicly accessible URL of the server you want to host the assets on and it should work. 

https://github.com/webpack/docs/wiki/configuration#outputpublicpath

**Comment by alphashuro** [comment]
ahh I see now, thank you :)
