### ISSUE TITLE
What's the reccomended way of accessing packaged assets like images?

### ISSUE THREAD

**Issue by dwjp** [owais/django-webpack-loader#54]
I have webpack configured to bundle up some images that are associated with my react components using file-loader. They are stored with my JS bundle, but require(..) just gives me the file name, not the full path.

Workaround at the moment is to hardcode in STATIC_PATH from django in addition to filename, or use url-loader instead to inline image data.

What's the suggested approach here?

**Comment by owais** [comment]
require should work properly. Try playing with `publicPath` setting and see if that works. Usually you'd want your `publicPath` and Django's `STATIC_URL` to be the same.

**Comment by owais** [comment]
https://github.com/webpack/docs/wiki/configuration#outputpublicpath

**Comment by dwjp** [comment]
Thanks, in my case: `publicPath: "/static/bundles/"`

**Comment by reywright** [comment]
@owais is there anyway for this to work a little bit more programmatically? Like if the build process for this plugin spit out a file with a string and we could just require that into the webpack build and then just put it in that one place. Would you consider this for a new feature? I don't know if having 2 places to manage where the STATIC_URL is, is maintainable.

**Comment by owais** [comment]
You can put common config in a json file and load it from both django settings and webpack config. 
Django:
```python
STATIC_URL = json.load(open('../webpack/common.json', 'r'))['STATIC_URL']
```


Webpack
```
var commonSettings = require('./common.json');
...
...
publicPath: commonSettings.STATIC_URL
```

That should let you set the value in a single place. I don't think it's worth it personally.

**Comment by owais** [comment]
Or you can pass it as ENV variable. I use makefiles to define some env vars and have make targets to calls django and webpack commands. Both can read the same env variables.
