### ISSUE TITLE
WEBPACK_LOADER example doesn't work

### ISSUE THREAD

**Issue by dhobbs** [owais/django-webpack-loader#56]
The following config, based on the example at http://owaislone.org/blog/webpack-plus-reactjs-and-django/ didn't work for me. I got the following error:
```
ERRORS:
django.conf.settings.WEBPACK_LOADER: (django-webpack-loader.E001) Error while parsing WEBPACK_LOADER configuration
	HINT: Is WEBPACK_LOADER config valid?
```

```
WEBPACK_LOADER = {
    'BUNDLE_DIR_NAME': 'bundles/',
    'STATS_FILE': join(SITE_ROOT, 'webpack-stats.json')
}
```

I had to set it like so to make it work:

```
WEBPACK_LOADER = {
    'DEFAULT': {
        'BUNDLE_DIR_NAME': 'bundles/',
        'STATS_FILE': join(SITE_ROOT, 'webpack-stats.json')}
}
```

**Comment by aleccunningham** [comment]
If you checkout the README, using `DEFAULT` is the documented way to go about modifying the settings. The example works just fine with the defaults (c/p from my `settings.py` file)
```Python
WEBPACK_LOADER = {
    'DEFAULT': {
        'CACHE': not DEBUG,
        'BUNDLE_DIR_NAME': 'bundles/',
        'STATS_FILE': os.path.join(BASE_DIR, 'webpack-stats.json'),
        'POLL_INTERVAL': 0.1,
        'IGNORE': ['.+\.hot-update.js', '.+\.map']
    }
}
```

**Comment by lenards** [comment]
I think this is related to #22.

**Comment by lenards** [comment]
And, @aleccunningham is correct.

**Comment by dhobbs** [comment]
Yes, exactly!

**Comment by lenards** [comment]
I forked Owais' blog - I'm going to PR the `settings.py` change now. 

Also, the React code is not valid as of 0.14.* because of the `'react-dom'` split. Least I can do for him creating this.

**Comment by aleccunningham** [comment]
Great. Love the idea of React + Django!

**Comment by owais** [comment]
Thanks so much guy!
