### ISSUE TITLE
Support timeouts in Debug mode

### ISSUE THREAD

**Issue by graup** [owais/django-webpack-loader#60]
We sometimes run into a "timeout" here:
https://github.com/owais/django-webpack-loader/blob/9eae37feedde87ed3fad994c592ecb623fb51357/webpack_loader/loader.py#L58

It would be great if that Todo could be implemented. It would be much nicer if the page would return an error after x (maybe 10?) seconds instead of waiting forever (or in our case the worker being killed by Gunicorn at some point).

**Comment by owais** [comment]
Implemented in 0.3.3 https://github.com/owais/django-webpack-loader#default-configuration

**Comment by graup** [comment]
Thank you!
