### ISSUE TITLE
Not rendering the hello world example in 'webpack-plus-reactjs-and-django

### ISSUE THREAD

**Issue by pwhipp** [owais/django-webpack-loader#62]
I have a react app working in django and am looking to use webpack to re-factor and streamline its ongoing development and maintenance.

Using [the blog entry](http://owaislone.org/blog/webpack-plus-reactjs-and-django/), all went well until I got to the actual presentation in Django.

I've copied the code pretty much verbatim save for putting it in a 'front_end' folder (paths etc. updated appropriately). The app.jsx file exports the class object fine but the render method on the object is never called (inserted console.log does not appear). In my other app example I use ReactDOM.render rather than React.render but apart from that it looks pretty similar.

The rest of the template comes up fine and it has included the bundle js correctly.

As the React debugger does not come up in Firefox and everything is mushed into the bundle (without any issues), I'm not sure where to go from here in terms of debugging.

**Comment by pwhipp** [comment]
OK - old school debugging sorted it slowly...

The React object does not have a render method any more so `index.jsx` must use the react-dom. To address this; `npm install react-dom` and change the main.js import/call to use `react-dom` appropriately.

Then we find that the jsx is not being handled by babel so still nothing gets rendered. This took me to [](https://github.com/babel/babel-loader) where I followed and used the instructions there to bring things up to date. This required installation of babel-preset-react.

Thus `package.json` became:
```javascript
{
  "name": "your name",
  "repository": {
    "type": "git",
    "url": "your repo"
  },
  "version": "1.0.0",
  "description": "react front end to django for xxx",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "whippy",
  "license": "ISC",
  "devDependencies": {
    "babel": "^6.5.2",
    "babel-cli": "^6.10.1",
    "babel-core": "^6.10.4",
    "babel-loader": "^6.2.4",
    "babel-preset-es2015": "^6.9.0",
    "babel-preset-react": "^6.5.0",
    "react": "^15.1.0",
    "react-dom": "^15.1.0",
    "webpack": "^1.13.1",
    "webpack-bundle-tracker": "0.0.93"
  }
}
```

`webpack.config.js` became:
```javascript
var path = require("path");
var webpack = require('webpack');
var BundleTracker = require('webpack-bundle-tracker');

module.exports = {
  context: __dirname,

  entry: './assets/js/index', // entry point of our app. assets/js/index.js should require other js modules and dependencies it needs

  output: {
      path: path.resolve('./assets/bundles/'),
      filename: "[name]-[hash].js"
  },

  plugins: [
    new BundleTracker({filename: './webpack-stats.json'})
  ],

  module: {
    loaders: [
      {
        test: /\.jsx?$/,
        exclude: /node_modules/,
        loader: 'babel-loader',
        query: {presets:['es2015', 'react']}}
    ]
  },

  resolve: {
    modulesDirectories: ['node_modules', 'bower_components'],
    extensions: ['', '.js', '.jsx']
  }
};
```

`index.jsx` became:
```javascript
//noinspection JSUnusedLocalSymbols because React is needed implicitly by babel's expansion.
var React = require('react');
var ReactDOM = require('react-dom');
var App = require('./app');

ReactDOM.render(<App/>, document.getElementById('react-app'));`
```

**Comment by owais** [comment]
Thanks @pwhipp. This should help others. I'll try to update the blog post soon to show latest version of babel
