### ISSUE TITLE
Change output name from main to app?

### ISSUE THREAD

**Issue by Ballpin** [owais/django-webpack-loader#65]
Is it possible to change main.js to app.js in the index.html?

I cant find it in the docs

**Comment by owais** [comment]
You can use a different name for your bundle by modifying the `entry` setting in your webpack configuration. If you just have a single entry point, the bundle will be called main. https://github.com/webpack/docs/wiki/configuration#entry

**Comment by Ballpin** [comment]
Ahh Thanks. Totally frogot about that.
