### ISSUE TITLE
Better error reporting.

### ISSUE THREAD

**Issue by waqasraz** [owais/django-webpack-loader#67]
I think it could be a good idea to report an error when someone user {% render_bundle 'XYZ' %} but the bundle is not declared. Currently, Django displays 

[http://prnt.sc/byb0u7](http://prnt.sc/byb0u7)
[http://prnt.sc/byb15c](http://prnt.sc/byb15c)

**Comment by ryanhiebert** [comment]
Obviously, the `KeyError` _is_ an error. How would you prefer to see this reported? Just another error type with a more descriptive message, or do you have something else in mind?

**Comment by waqasraz** [comment]
Something like bundle_name does not exist.

 Because my settings file name was "common" and yesterday I was getting error keyerror at / "common". Just saying could be easier for a newbie to webpack-loader.

**Comment by owais** [comment]
@waqasraz Sounds reasonable. I'd be happy to take a patch :)
