### ISSUE TITLE
How to clear cache after rebuild webpack

### ISSUE THREAD

**Issue by vinhlh** [owais/django-webpack-loader#68]
How to clear cache after rebuild webpack

**Comment by owais** [comment]
Do you mean this cache: https://github.com/owais/django-webpack-loader/#cache

At the moment, it can not be invalidated. You'll have to restart the python process to clear it and reload the file or you can turn it off if that doesn't work for you.

**Comment by vinhlh** [comment]
but, we can add a command to Django to remove the cache key, right?
@owais

**Comment by owais** [comment]
There is no cache key. There is no actual "caching" going on. We just read the file once and keep it in memory forever.
