### ISSUE TITLE
render_bundle template tag cannot be used to load gzipped files

### ISSUE THREAD

**Issue by mikeengland** [owais/django-webpack-loader#74]
If you want to serve gzipped files (say, those created by [https://github.com/webpack/compression-webpack-plugin](url)), the render_bundle template tag cannot serve these.

Even if you specify js.gz as the extension, e.g. `{% render_bundle 'main' 'js.gz' %}`, the `render_as_tags` function will not pick up these files. This is because `chunk['name'].endswith('.js')` and `chunk['name'].endswith('.css')` are used. I suggest this is changed to allow for '.js.gz' and '.css.gz' files as well.

As a temporary work around, a direct link to the content can be used, e.g. <script type="text/javascript" src="/static/bundles/main.js.gz"></script>
 but this is not ideal.

**Comment by owais** [comment]
Makes sense. Would you be willing to submit a patch/PR to fix this? If you are not able to for some reason, I'll fix it some time next week.

**Comment by mikeengland** [comment]
Hey @owais, sure, I will try and create a pull req for this over the next few days. Are there any extensions aside from .js.gz/.css.gz to cater for? I could just do a regex match on *.js.* and *.css.* if that sounds reasonable?

**Comment by owais** [comment]
Regex on `.js.` sounds good except some people could have `.js.css` :D 

I think we can still try regex like behaviour to detect the type of HTML tag we can use if we allow users to override the behaviour from the template. May be something like,

```django
{% render_bundle 'main' tag='script' %}
```
would always use a `<script>` tag irrespective of file extension.

**Comment by owais** [comment]
but still a simpler (may be better) approach is to hard code for the exact extensions we expect and map them to type of tags like we have now.

**Comment by Zigur** [comment]
Could you publish a pip package with this feature? Thanks a lot!

**Comment by owais** [comment]
Released `0.4.0`. Thanks.

**Comment by jameshiew** [comment]
The node package webpack-bundle-tracker isn't tracking gzipped files, so this still isn't working out of the box as far as I can tell - see issue https://github.com/ezhome/webpack-bundle-tracker/issues/22

**Comment by Gaabe** [comment]
Is there a solution for this yet? As @jameshiew  said, the webpack bundle tracker still doesn't track the .gz files created.

**Comment by jonalxh** [comment]
Is it working now? I have .br and .gz files and want to use them.
