### ISSUE TITLE
using webpack-loader with nginx/gunicorn

### ISSUE THREAD

**Issue by kevinmachstudio** [owais/django-webpack-loader#89]
Hi, 

Are there any examples of django-webpack-loader being used with Gunicorn and Nginx? It works perfectly when I'm developing locally but doesn't work on the production. It doesn't render my bundle file since it's treating it as a string, even though I've installed it on my production server too.

{% load render_bundle from webpack_loader %}
{% render_bundle 'main' 'js' %}

Any ideas why this is happening?

**Comment by owais** [comment]
This doesn't really have much to do with django-webpack-loader. Just make sure all other assets are being served by nginx on production fine and that your webpack generated bundles are being collected by django's collectstatic command. 

More on this:

https://docs.djangoproject.com/en/1.10/howto/static-files/
https://docs.djangoproject.com/en/1.10/ref/contrib/staticfiles/
