### ISSUE TITLE
Singleton manifest

### ISSUE THREAD

**Issue by markfinger** [owais/django-webpack-loader#9]
Hey @owais 

I was hoping to use your lib with a decoupled app which ships with pre-built bundles. As far as I can tell, it only allows you to use a single manifest, which looks like it'd preclude any other apps from trying to use the loader.

Is there anyway to override the manifest path?

Something like the following would be cool

```python
import os
from webpack_loader.utils import read_bundle_from_manifest

manifest_path = os.path.join(os.path.dirname(__file__), 'webpack-manifest.json')

bundle = read_bundle_from_manifest(manifest_path)

bundle.render_css()
bundle.render_js()
```

or even

```
{% load render_bundle from webpack_loader %}

{% render_bundle 'main' 'css' path_to_manifest %}
{% render_bundle 'main' 'js' path_to_manifest %}
```

**Comment by markfinger** [comment]
As a temporary work around, I've ended up just hard-coding the paths and letting django-compressor generate hashed file names. Sadly though, this breaks `url(..)` refs in the css :(

**Comment by owais** [comment]
Would something like, 
```
WEBPACK_LOADER = {
    'STATS_FILES': {
          'default': os.path.join(BASE_DIR, 'webpack-stats.json'),
          'internal-app': os.path.join(BASE_DIR, 'webpack-stats-internal.json')
     }
}
```

and then
```
{% render_bundle 'main' 'css'  %} # would load from default
{% render_bundle 'main' 'css'  'internal-app' %}
```

solve it?

**Comment by markfinger** [comment]
I think that would solve some of the problem, and it would also make it easier for projects that are consuming an app to override parts of it. 

That being said, I'm a bit unsure about a decoupled app relying on both constants and paths that are defined in a downstream project's settings. For this particular use-case it would make it difficult to have pre-built bundles & stats living in a virtualenv somewhere, so it looks like you'd lose a lot of portability. I suppose you *could* introspect an app to resolve a path, with the cost that there's more magic in your setting files.

**Comment by owais** [comment]
Hmm. I'm not sure I understand the problem completely but looks like you want to ship a python module which includes a pre-built bundle as a data file and then want to be able to use this pre-built module in the actual project. If that's what you are doing then I'm not sure how django-webpack-loader can help. In my mind, the use upstream package used webpack-loaded only during development and then ships the pre-built bundle at a standard location or provides a custom python function to get hold of the bundle. if the package is a django app, it could ship the pre-built bundle as part of staticfiles as well and get django integration for free. I'm not sure if webpack-loader should care about loading bundles shipped with other apps.

**Comment by markfinger** [comment]
Fair enough - I've ended up hard-coding the urls so it's all good.

Primarily, I was hoping to use your lib as a hook to easily pull in files with hashed paths, the benefit being cache busting on deployments. But, I suppose compressor will work just as well.

Thanks @owais
